language: bash

before_install:
  - sudo apt-get update && sudo apt install -y shellcheck p7zip-full imagemagick ghostscript

script:
  - ls -l
  - shellcheck Task1-ProcessImages.sh
  - ls -al ./img
  - bash Task1-ProcessImages.sh -h
  - bash Task1-ProcessImages.sh -q ./img 50
  - bash Task1-ProcessImages.sh -r ./img 80%
  - bash Task1-ProcessImages.sh -w ./img dzr SouthWest 10 y
  - bash Task1-ProcessImages.sh -p ./img p
  - bash Task1-ProcessImages.sh -s ./img s
  - bash Task1-ProcessImages.sh -t ./img
  - ls -al ./img
  - shellcheck Task2-ProcessFile.sh
  - echo Task2
  - bash Task2-ProcessFile.sh -h
  - bash Task2-ProcessFile.sh -a
  - bash Task2-ProcessFile.sh -p
  - bash Task2-ProcessFile.sh -n
  - bash Task2-ProcessFile.sh -m
  - shellcheck Task3-ProcessFile.sh
  - echo Task3
  - bash Task3-ProcessFile.sh -h
  - bash Task3-ProcessFile.sh -t
  - bash Task3-ProcessFile.sh -i
  - bash Task3-ProcessFile.sh -u
  - bash Task3-ProcessFile.sh -s
  - bash Task3-ProcessFile.sh -c
  - bash Task3-ProcessFile.sh -f /images/ksclogo.gif

notifications:
  email:
    on_success: never
